// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: common/dto/dto_auth_feature_ping_ping.dto.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthPingRequest) Reset() {
	*x = AuthPingRequest{}
	mi := &file_common_dto_dto_auth_feature_ping_ping_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPingRequest) ProtoMessage() {}

func (x *AuthPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_dto_dto_auth_feature_ping_ping_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPingRequest.ProtoReflect.Descriptor instead.
func (*AuthPingRequest) Descriptor() ([]byte, []int) {
	return file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescGZIP(), []int{0}
}

type AuthPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthPingResponse) Reset() {
	*x = AuthPingResponse{}
	mi := &file_common_dto_dto_auth_feature_ping_ping_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPingResponse) ProtoMessage() {}

func (x *AuthPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_dto_dto_auth_feature_ping_ping_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPingResponse.ProtoReflect.Descriptor instead.
func (*AuthPingResponse) Descriptor() ([]byte, []int) {
	return file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescGZIP(), []int{1}
}

func (x *AuthPingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_dto_dto_auth_feature_ping_ping_dto_proto protoreflect.FileDescriptor

const file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDesc = "" +
	"\n" +
	"/common/dto/dto_auth_feature_ping_ping.dto.proto\x12\x03dto\"\x11\n" +
	"\x0fAuthPingRequest\",\n" +
	"\x10AuthPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\aZ\x05./dtob\x06proto3"

var (
	file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescOnce sync.Once
	file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescData []byte
)

func file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescGZIP() []byte {
	file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescOnce.Do(func() {
		file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDesc), len(file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDesc)))
	})
	return file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDescData
}

var file_common_dto_dto_auth_feature_ping_ping_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_dto_dto_auth_feature_ping_ping_dto_proto_goTypes = []any{
	(*AuthPingRequest)(nil),  // 0: dto.AuthPingRequest
	(*AuthPingResponse)(nil), // 1: dto.AuthPingResponse
}
var file_common_dto_dto_auth_feature_ping_ping_dto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_dto_dto_auth_feature_ping_ping_dto_proto_init() }
func file_common_dto_dto_auth_feature_ping_ping_dto_proto_init() {
	if File_common_dto_dto_auth_feature_ping_ping_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDesc), len(file_common_dto_dto_auth_feature_ping_ping_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_dto_dto_auth_feature_ping_ping_dto_proto_goTypes,
		DependencyIndexes: file_common_dto_dto_auth_feature_ping_ping_dto_proto_depIdxs,
		MessageInfos:      file_common_dto_dto_auth_feature_ping_ping_dto_proto_msgTypes,
	}.Build()
	File_common_dto_dto_auth_feature_ping_ping_dto_proto = out.File
	file_common_dto_dto_auth_feature_ping_ping_dto_proto_goTypes = nil
	file_common_dto_dto_auth_feature_ping_ping_dto_proto_depIdxs = nil
}
